name: mek_floating_drag
description: Enable a widget to be dragged allowing it to be removed if dropped in an area or hidden if time passes or is pressed out
version: 0.1.0
repository: https://github.com/BreX900/mek_floating_drag

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mek_lints: ^0.3.0

flutter:

index_generator:
  exclude:
    - '**/utils/**'
  indexes:
    - path: lib