name: mek_floating_drag
description: Enable a widget to be dragged allowing it to be removed if dropped in an area or hidden if time passes or is pressed out
version: 0.0.1
repository:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

index_generator:
  exclude:
    - '**/utils/**'
  indexes:
    - path: lib