name: Example Web App
on:
  push:
    branches:
      - master
    # paths:
    #   - 'form_bloc_web/**'
    #   - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./form_bloc_web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ env.working-directory }}

      - name: Build web
        run: flutter build web --web-renderer html
        working-directory: ${{ env.working-directory }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./example/build/web